#include <vector>
#include <string>

std::vector <std::string> five_syllables = {
    "i have to call chuck",
    "rebel boat rocker",
    "colostomy bag",
    "walking in memphis",
    "exploding midget",
    "white cotton panties",
    "nub technology",
    "anonymous nub",
    "more bunny justice",
    "evil evil boy",
    "you have been a fool",
    "do not send me porn ",
    "i must escape it",
    "those creamy white thighs",
    "keeping us all cool ",
    "air conditioning",
    "so what if I sweat",
    "fresh air is so sweet",
    "live mice sit on us ",
    "digital squirrel",
    "liquid banana",
    "peas and hominy ",
    "miscellaneous",
    "gravity assist",
    "random tuna head",
    "some quick goat thinking",
    "a velvet codpiece",
    "let's tease the weasels",
    "nice vomiting spell",
    "a specific dick ",
    "the growing yodas"
};

std::vector <std::string> seven_syllables = {
    "the half-life of lime jello",
    "nuclear bedtime story",
    "crazy customizable",
    "programmer's head on a stick",
    "frictionless, massless mormon",
    "put it in your report, bill ",
    "i don't need the influence",
    "i'm coming out of the booth ",
    "in the middle of a storm",
    "it tantalizes me so ",
    "you are my favorite thing",
    "i leave the windows open",
    "and fed you to the chickens ",
    "candy corn chicken fetus",
    "the silhouette of a dog ",
    "guns exploding all around",
    "a rising column of smoke",
    "you don't jump like a monkey"
};
